# Script: Set-PublicGroupsToPrivateFromCSV.ps1
# Purpose: Switches Microsoft 365 Groups listed in a CSV file from Public to Private.
# Author: FakeIT (AI Assisted)
# Date: March 06, 2025
# Notes:
# - Requires ExchangeOnlineManagement module (Install-Module -Name ExchangeOnlineManagement).
# - Must run with Exchange Admin or Global Admin permissions.
# - Reads from PublicGroups.csv on Desktop (generated by Export-PublicGroupsToCSV.ps1).
# - Sets groups to Private, allowing self-joining requests with owner approval (SubscriptionEnabled unchanged).

# Connect to Exchange Online service to manage Microsoft 365 Groups
# Establishes a session using modern authentication
Connect-ExchangeOnline

# Import the CSV file containing Public groups to be modified
# Assumes the CSV is on the Desktop, created by the companion script
$groupsToChange = Import-Csv -Path "$env:USERPROFILE\Desktop\PublicGroups.csv"

# Check if the CSV contains any groups to process
# If data exists, proceed with changes; otherwise, notify the user
if ($groupsToChange) {
    # Display the number of groups to be changed for user awareness
    Write-Host "Switching $($groupsToChange.Count) groups to Private..."
    
    # Iterate through each group listed in the CSV
    foreach ($group in $groupsToChange) {
        # Set the group to Private using its Identity from the CSV
        # -AccessType Private restricts visibility and access to members only
        # Self-joining requests remain possible (if SubscriptionEnabled is $true), requiring owner approval
        Set-UnifiedGroup -Identity $group.Identity -AccessType Private
        
        # Confirm each change with the group's display name for logging
        Write-Host "Changed $($group.DisplayName) to Private"
    }
    
    # Notify completion of the operation
    Write-Host "All groups from CSV switched to Private."
} else {
    # Handle cases where the CSV is missing or empty
    Write-Host "No groups found in PublicGroups.csv or CSV is empty."
}

# Disconnect from Exchange Online session
# -Confirm:$false skips the confirmation prompt for a clean exit
Disconnect-ExchangeOnline -Confirm:$false
